#!/usr/bin/env python3
"""
pipeline.py — Orchestrator + Scheduler for the local video factory.

Usage:
    python pipeline.py --run-now              # Run one video immediately
    python pipeline.py --run-now --seed=42    # Reproducible run
    python pipeline.py --schedule             # Start scheduler (every 3 days)
"""

import argparse
import json
import logging
import re
import shutil
import sys
import traceback
from datetime import datetime
from pathlib import Path
from typing import Optional

from brain import (
    OUTPUT_ROOT,
    generate_narration,
    generate_shorts,
    ingest_pdfs,
    pick_topic,
    produce_video,
    setup_logging,
    write_script,
)

logger = logging.getLogger("pipeline")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
CONFIG_PATH = Path(__file__).parent / "pipeline_config.json"

DEFAULT_CONFIG = {
    "schedule_days": 3,
    "auto_publish": False,
    "edge_tts_voice": "en-US-AndrewMultilingualNeural",
    "ollama_model": "qwen3:8b",
    "pexels_api_key": "",
    "skip_mpt": False,       # Skip MPT stage (for testing without Pexels key)
    "skip_clipper": False,   # Skip vid-clipper stage
}


def load_config() -> dict:
    """Load pipeline configuration, creating defaults if needed."""
    if CONFIG_PATH.exists():
        with open(CONFIG_PATH, "r") as f:
            config = json.load(f)
        # Merge with defaults for any missing keys
        for key, val in DEFAULT_CONFIG.items():
            config.setdefault(key, val)
        return config
    else:
        with open(CONFIG_PATH, "w") as f:
            json.dump(DEFAULT_CONFIG, f, indent=2)
        return dict(DEFAULT_CONFIG)


# ---------------------------------------------------------------------------
# Report Generation
# ---------------------------------------------------------------------------

def generate_report(task_dir: Path, topic: dict, script_data: dict,
                    narration_path: Optional[Path],
                    final_video: Optional[Path],
                    short_clips: list[Path],
                    error: Optional[str] = None) -> Path:
    """Generate REPORT.md summarizing the pipeline run."""
    report_path = task_dir / "REPORT.md"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    status = "✅ COMPLETE" if final_video and final_video.exists() else "❌ FAILED"
    if error:
        status = f"❌ FAILED: {error}"

    sources_md = ""
    for src in script_data.get("sources", []):
        sources_md += f"- **{src.get('pdf', 'N/A')}**, page {src.get('page', '?')}: _{src.get('quote', '')}_\n"

    clips_md = ""
    for clip in short_clips:
        size_mb = clip.stat().st_size / (1024 * 1024) if clip.exists() else 0
        clips_md += f"- `{clip.name}` ({size_mb:.1f} MB)\n"

    report = f"""# Video Factory — Run Report

**Status**: {status}
**Generated**: {timestamp}
**Seed**: {topic.get('seed', 'N/A')}

---

## Topic Selection

| Field | Value |
|-------|-------|
| PDF | {topic.get('pdf_filename', 'N/A')} |
| Topic | {topic.get('topic', 'N/A')} |
| Angle | {topic.get('angle', 'N/A')} |
| Target Duration | {topic.get('target_seconds', 'N/A')}s |

---

## Script

{script_data.get('script', '_No script generated_')}

### Sources (traceable to PDF)
{sources_md if sources_md else '_No sources cited_'}

### Keywords
{', '.join(script_data.get('keywords', []))}

---

## Generated Files

| Asset | Path | Size |
|-------|------|------|
| Narration | `{narration_path.name if narration_path and narration_path.exists() else 'N/A'}` | {f'{narration_path.stat().st_size / (1024*1024):.1f} MB' if narration_path and narration_path.exists() else 'N/A'} |
| Full Video | `{final_video.name if final_video and final_video.exists() else 'N/A'}` | {f'{final_video.stat().st_size / (1024*1024):.1f} MB' if final_video and final_video.exists() else 'N/A'} |

### Short Clips (9:16)
{clips_md if clips_md else '_No clips generated_'}

---

## Upload Checklist

- [ ] Watch the video end-to-end — verify facts match the source PDF
- [ ] Set audience = **Not-for-kids**
- [ ] Set AI-disclosure = **YES**
- [ ] Paste the sources list below into the video description
- [ ] Add hashtags from keywords above

### Description Template

```
{topic.get('topic', 'Quantum Computing')}

Sources:
{chr(10).join(f"• {s.get('pdf', '')} p.{s.get('page', '?')}" for s in script_data.get('sources', []))}

#quantum #science #education #physics #shorts
```

---

> ⚠️ DEFAULT = DO NOT AUTO-PUBLISH. The human verifies before upload.

Generated by Video Factory Pipeline
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)

    logger.info(f"Report saved: {report_path}")
    return report_path


# ---------------------------------------------------------------------------
# Main Pipeline
# ---------------------------------------------------------------------------

def run_one_video(seed: Optional[int] = None, config: Optional[dict] = None) -> Path:
    """
    Run the complete video generation pipeline for one video.
    Stages are serialized to respect GPU memory constraints.

    Returns the task directory path.
    """
    if config is None:
        config = load_config()

    if seed is None:
        seed = int(datetime.now().timestamp()) % 100000

    # Create task directory
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    task_dir = OUTPUT_ROOT / "tasks" / f"{timestamp}_seed{seed}"
    task_dir.mkdir(parents=True, exist_ok=True)

    log_dir = OUTPUT_ROOT / "logs"
    setup_logging(log_dir)

    logger.info("=" * 60)
    logger.info(f"VIDEO FACTORY — Starting run (seed={seed})")
    logger.info(f"Task directory: {task_dir}")
    logger.info("=" * 60)

    topic = {}
    script_data = {}
    narration_path = None
    final_video = None
    short_clips = []
    error_msg = None

    try:
        # ── Stage 1: PDF Ingestion ──────────────────────────────────
        logger.info("━━━ STAGE 1: PDF Ingestion ━━━")
        index_path = OUTPUT_ROOT / "library_index.json"
        if not index_path.exists():
            index_path = ingest_pdfs()
        else:
            logger.info("Using existing library index")

        # ── Stage 2a: Topic Selection ───────────────────────────────
        logger.info("━━━ STAGE 2a: Topic Selection ━━━")
        topic = pick_topic(index_path, task_dir, seed=seed)
        logger.info(f"Topic: {topic.get('topic')}")

        # ── Stage 2b: Script Writing ────────────────────────────────
        logger.info("━━━ STAGE 2b: Script Writing ━━━")
        script_data = write_script(topic, index_path, task_dir, seed=seed)
        script_text = script_data.get("script", "")
        logger.info(f"Script: {len(script_text.split())} words, "
                     f"{len(script_data.get('sources', []))} sources")

        # ── Stage 3: TTS Narration ──────────────────────────────────
        logger.info("━━━ STAGE 3: TTS Narration ━━━")
        narration_path = generate_narration(script_text, task_dir)
        logger.info(f"Narration: {narration_path}")

        # ── Stage 4: MPT Video Production ───────────────────────────
        if not config.get("skip_mpt", False):
            logger.info("━━━ STAGE 4: Video Production (MPT) ━━━")
            final_video = produce_video(script_data, narration_path, topic, task_dir)
            logger.info(f"Video: {final_video}")
        else:
            logger.info("━━━ STAGE 4: SKIPPED (skip_mpt=True) ━━━")

        # ── Stage 5: Short Clips ────────────────────────────────────
        if not config.get("skip_clipper", False) and final_video and final_video.exists():
            logger.info("━━━ STAGE 5: Short Clips (vid-clipper) ━━━")
            short_clips = generate_shorts(final_video, task_dir)
            logger.info(f"Shorts: {len(short_clips)} clips")
        else:
            logger.info("━━━ STAGE 5: SKIPPED ━━━")

        # ── Copy to ready/ ──────────────────────────────────────────
        ready_dir = OUTPUT_ROOT / "ready"
        ready_dir.mkdir(parents=True, exist_ok=True)

        if final_video and final_video.exists():
            import shutil
            slug = re.sub(r'[^\w]', '_', topic.get('topic', 'video'))[:50]
            ready_name = f"{timestamp}_{slug}"
            ready_video = ready_dir / f"{ready_name}.mp4"
            shutil.copy2(final_video, ready_video)
            logger.info(f"Ready: {ready_video}")

            for clip in short_clips:
                if clip.exists():
                    shutil.copy2(clip, ready_dir / f"{ready_name}_{clip.name}")

        logger.info("✅ Pipeline completed successfully!")

    except Exception as e:
        error_msg = str(e)
        logger.error(f"❌ Pipeline failed: {e}")
        logger.error(traceback.format_exc())

    # ── Generate Report ─────────────────────────────────────────────
    report = generate_report(
        task_dir, topic, script_data, narration_path,
        final_video, short_clips, error_msg
    )

    # ── Desktop Notification ────────────────────────────────────────
    try:
        import subprocess
        status = "COMPLETE ✅" if not error_msg else f"FAILED ❌"
        topic_name = topic.get("topic", "Unknown")
        subprocess.run([
            "powershell", "-Command",
            f'[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType=WindowsRuntime] | Out-Null; '
            f'$xml = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02); '
            f'$text = $xml.GetElementsByTagName("text"); '
            f'$text[0].AppendChild($xml.CreateTextNode("Video Factory: {status}")) | Out-Null; '
            f'$text[1].AppendChild($xml.CreateTextNode("{topic_name}")) | Out-Null; '
            f'$toast = [Windows.UI.Notifications.ToastNotification]::new($xml); '
            f'[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier("Video Factory").Show($toast)'
        ], capture_output=True, timeout=10)
    except Exception:
        pass  # Non-critical

    return task_dir


# ---------------------------------------------------------------------------
# Scheduler
# ---------------------------------------------------------------------------

def run_scheduler(config: dict):
    """Run the pipeline on a schedule using APScheduler."""
    from apscheduler.schedulers.blocking import BlockingScheduler

    interval_days = config.get("schedule_days", 3)
    logger.info(f"Starting scheduler: every {interval_days} days")

    scheduler = BlockingScheduler()
    scheduler.add_job(
        run_one_video,
        "interval",
        days=interval_days,
        kwargs={"config": config},
        id="video_factory",
        name="Video Factory Pipeline",
        next_run_time=datetime.now(),  # Run immediately on start
    )

    try:
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        logger.info("Scheduler stopped")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

# Need this import at module level for the slug generation
import re

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Video Factory Pipeline")
    parser.add_argument("--run-now", action="store_true",
                        help="Run one video immediately")
    parser.add_argument("--schedule", action="store_true",
                        help="Start the scheduler")
    parser.add_argument("--seed", type=int, default=None,
                        help="Random seed for reproducibility")
    parser.add_argument("--skip-mpt", action="store_true",
                        help="Skip MoneyPrinterTurbo stage")
    parser.add_argument("--skip-clipper", action="store_true",
                        help="Skip vid-clipper stage")

    args = parser.parse_args()
    config = load_config()

    if args.skip_mpt:
        config["skip_mpt"] = True
    if args.skip_clipper:
        config["skip_clipper"] = True

    if args.run_now:
        task_dir = run_one_video(seed=args.seed, config=config)
        print(f"\n{'='*60}")
        print(f"  Task directory: {task_dir}")
        print(f"  Report: {task_dir / 'REPORT.md'}")
        print(f"{'='*60}")

    elif args.schedule:
        run_scheduler(config)

    else:
        parser.print_help()
